version: '3.8'

networks: 
 diananet:

services:
 flask:
  build:
   context: .
  ports:
    - 8080:8080
  networks: 
    - diananet
  env_file:
    - .env

 neo4j:
  container_name: neo4j-dev
  image: neo4j
  ports:
    - 7474:7474
    - 7687:7687
  environment:
    - NEO4J_AUTH=neo4j/test
  networks: 
    - diananet