version: "3.7"

services:
  webapp:
    image: loreand/webapp
    ports:
      - 3000:3000
  movieservice:
    image: loreand/movieservice
    ports:
      - 3005:3005
  shopservice:
    image: loreand/shopservice
    ports:
      - 3006:3006
  reviewservice:
    image: loreand/reviewservice
    ports:
      - 3007:3007
  userservice:
    image: loreand/userservice
    ports:
      - 8080:8080