version: "3.7"

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 80:3000
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - 8080:8080