version: "3.7"

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  movieservice:
    build:
      context: ./movieservice
      dockerfile: Dockerfile
    ports:
      - 3005:3005
  shopservice:
    build:
      context: ./shopservice
      dockerfile: Dockerfile
    ports:
      - 3006:3006
  reviewservice:
    build:
      context: ./reviewservice
      dockerfile: Dockerfile
    ports:
      - 3007:3007
  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - 8080:8080