FROM tomcat:8.5

MAINTAINER loreand

COPY actorservice.war /usr/local/tomcat/webapps/actorservice.war
COPY movieservice.war /usr/local/tomcat/webapps/movieservice.war
COPY payservice.war /usr/local/tomcat/webapps/payservice.war
COPY reviewservice.war /usr/local/tomcat/webapps/reviewservice.war
COPY shopservice.war /usr/local/tomcat/webapps/shopservice.war
COPY userservice.war /usr/local/tomcat/webapps/userservice.war